### PR TITLE
Add CMakeLists.txt project file

### PR DESCRIPTION
**Pull request by NeroBurner**
To build the project use the following commands:

```sh
cmake -S . -B build -DCMAKE_INSTALL_PREFIX="${PWD}/install"
cmake --build build -j4 --target install
```

The `CMAKE_INSTALL_PREFIX` part is optional, but enables you to set the
installation directory.

The above commands use an "out of source" build. This means all the
build files are in the specified build folder `build`. This helps keep
the repository clean of generated files, and makes it easier to switch
between build types, C++ standards or other things to try out.

The above commands are OS independent, which means you can build with
the commands on different platforms.

To build a 'Debug' build use the variable `CMAKE_BUILD_TYPE`. For
example:

```sh
cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
cmake --build build -j4
```

The `-j4` is used to build with 4 parallel threads. This can be any
number or with `-j` all the possible threads are used.

### CODE REVIEW

**Comment by Bollos00** [comment]
Hello and thank you for your contributions,

CMake seems to be a more universal build system (and even more powerful) than QMake. Even though QMake is more easy-to-use and more convenient for Qt Applications, CMake would allow us to do more complex stuff. Although I am not sure if this project will ever be more complex, the decision to change the build system to CMake seems reasonable. Moreover CMake seems to be more customizable about the installation parameters.

Anyway, I think it is appropriate to use just one build system (QMake or CMake), so the best would be to remove the `LibreMines.pro` file and edit the build instructions on the README file.

**Comment by NeroBurner** [comment]
Updated the commit with removal of the pro file and updated build steps in `README.md`

**Comment by Bollos00** [comment]
Merging, thank you for your contribution.

**Comment by NeroBurner** [comment]
you're welcome :)

**Pull request merged**
