### PR TITLE
I added a new "Flowerfield" theme for LibreMines

### PR DESCRIPTION
**Pull request by SecularSteve**
flowerfield

It's supposed to be based on the "Flower Garden" theme from the Windows Vista/7 Minesweeper iteration.
A more "Child-friendly" variant, I guess you could say.

I especially loved those ambient sounds every time you stepped on a flower.

In case I missed a spot, feel free to point it out. I'm not some super-powered genius.
In case you think that there could be some changes made, feel free to let me know.

Made in Inkscape, the Numbers use the "Lily" font, it's under the CC BY-SA 4.0

### CODE REVIEW

**Comment by SecularSteve** [comment]
P.S.
There's two things that need to be corrected.

1. The folder within a folder.
2. The placeholder needs to be removed.

**Comment by Bollos00** [comment]
Hi there. Sorry for the delay and thanks to your interest in contributing to libremines.

As you said, the 'folder within a folder' change. The theme folder should be as [explained here](https://github.com/SecularSteve/LibreMines/tree/SecularSteve-flowerfield_theme/share/minefield_themes). The new theme can be installed as a cmake option like `alternative_dark` and `alternative_light` themes.

I tested it here, but unfortunately it does not seen to work as expected here... See the screenshot.

Screenshot_20220214_025212

The five files bellow open correctly on inkscape, but not by the qt engine. I believe that this is an issue with the qt framework and I may search for a workaround for it.
- boom.svg
- flag.svg
- mine.svg
- no_flag.svg
- wrong_flag.svg

The font size of the numbers appear a little big for me, but it is weird that I do not see those at all on the minefield...

Screenshot_20220214_030503

**Comment by SecularSteve** [comment]
I see...

As for the last part, it must be another one of those "Object to Path" issues in Inkscape when it comes to font size.

I'll send over the "flattened" 0-8 numbers today if I can.

**Comment by Bollos00** [comment]
Screenshot_20220214_033531

I managed to make the qt engine load the svg files properly by "picking the color" and then "filling on the right places". It is silly but solves the issue. I do not know it there is a better solution tho...


[flowerfield.zip](https://github.com/Bollos00/LibreMines/files/8058431/flowerfield.zip)

Here are some of the files

**Comment by Bollos00** [comment]
> I'll send over the "flattened" 0-8 numbers today if I can.

There is no hurry. You can do it when you get time ;)

**Comment by SecularSteve** [comment]
I'm finished (I think)...
Make sure just in case, and use all of the numbers this time. It will look so much better.

**Comment by Bollos00** [comment]
Screenshot_20220215_115036

The numbers are displayed correctly now. I will just do the workaround for the qt.svg  to properly loads the image.

**Comment by Bollos00** [comment]
It is nice, @SecularSteve. Congratulations!

Screenshot_20220216_220822
Screenshot_20220216_220654

**Comment by Bollos00** [comment]
[flowerfield.zip](https://github.com/Bollos00/LibreMines/files/8084726/flowerfield.zip)

Here it is the svg files with the workaround that I mentioned.

**Comment by SecularSteve** [comment]
Should I add that last piece of code mentioned above, or?

**Comment by Bollos00** [comment]
Great. Now after you undo the changes made on [share/minefield_themes.qrc](https://github.com/Bollos00/LibreMines/pull/41/files/3ac2c3313b2cb4da8eb396162c0d50d5cd6f6776#diff-ed878b35736881675a731eb12fc10f00d07ec31e528bd724dc57a53e5b1fac6c) and replace the current svg files of flowerfield theme with the ones that I uploaded in [this comment](https://github.com/Bollos00/LibreMines/pull/41#issuecomment-1042468678), I can close the finish this pull request

**Comment by SecularSteve** [comment]
I think I'm done.
Check if you can just in case.

**Comment by Bollos00** [comment]
Merged. Thank you for your contribution 🤝

**Pull request merged**
