### PR TITLE
Made new "Custom Emojis" for the reactions

### PR DESCRIPTION
**Pull request by SecularSteve**
custom_emoji

Now that "Flowerfield's" done with, I've got a new theme for the Faces to suggest.

My own creation. I decided to give the game a "non-corporate" spice.
Something for people looking for just a pinch more of a personality for something that's otherwise a simple but fun game.

Made entirely in Inkscape, under the CC BY-SA 4.0 license.

### CODE REVIEW

**Comment by Bollos00** [comment]
These look real nice. Congratulations. I will merge it into a new branch and then do the necessary changes to implement the new theme on the game.

What will be the theme name?

**Comment by SecularSteve** [comment]
I've been thinking of just leaving it at "SecularSteve_Custom", or "SecularSteve's CustomMojis" but if you want some creativity behind it, I'd go with these ones:
-AntonucciMoji
-DrawMoji
-HandMoji
-PersonaliMojis

I mean, depends on which you think is the best...

**Comment by Bollos00** [comment]
I liked HandMoji. But it is your choice.

**Comment by SecularSteve** [comment]
How about "SecularSteve's HandMojis".
Or just "Handmojis" to correspond with what I presume are guidelines of the CC BY-SA 4.0 licence.

**Comment by SecularSteve** [comment]
While I'm at it, I'd like to suggest a new logo for LibreMines itself.
The current one feels a bit "DOS-ish" in my opinion.

libremines

**Comment by Bollos00** [comment]
The logo looks really nice. But I am not interested in switching it.

**Pull request merged**
